import os
import re

def process_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()

    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
        else:
            print(f"Warning: Could not find '{old}' in {filepath}")

    with open(filepath, 'w') as f:
        f.write(content)

# persistent_engine.rs
process_file("relvar-storage/src/persistent_engine.rs", [
    (
        "pub struct PersistentSnapshot {",
        "/// Snapshot for persistent transactions.\n///\n/// Represents the state of a transaction at a specific point in time.\n/// It ensures that operations are performed within the correct concurrency context.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::wal::TransactionId;\n/// use relvar_storage::persistent_engine::PersistentSnapshot;\n///\n/// let snapshot = PersistentSnapshot { txn_id: TransactionId::new(42) };\n/// assert_eq!(snapshot.txn_id.value(), 42);\n/// ```\npub struct PersistentSnapshot {"
    )
])

# wal/lsn.rs
process_file("relvar-storage/src/wal/lsn.rs", [
    (
        "pub struct Lsn(u64);",
        "/// Log Sequence Number - uniquely identifies a position in the WAL.\n///\n/// LSNs are monotonically increasing and provide a total ordering of\n/// all log records. They are used to determine which operations happened\n/// before others during recovery.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::wal::Lsn;\n///\n/// let lsn1 = Lsn::new(1);\n/// let lsn2 = Lsn::new(2);\n///\n/// assert!(lsn1 < lsn2);\n/// assert_eq!(lsn1.next(), lsn2);\n/// ```\npub struct Lsn(u64);"
    ),
    (
        "pub struct TransactionId(u64);",
        "/// Unique identifier for a transaction.\n///\n/// TransactionIds are generated by `TransactionIdGenerator` and uniquely\n/// identify a transaction within the database. They are separate from LSNs\n/// because a single transaction may generate multiple log records.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::wal::TransactionId;\n///\n/// let txn1 = TransactionId::new(1);\n/// let txn2 = TransactionId::new(2);\n///\n/// assert_ne!(txn1, txn2);\n/// ```\npub struct TransactionId(u64);"
    )
])

# wal/record.rs
process_file("relvar-storage/src/wal/record.rs", [
    (
        "pub enum WalRecordError {",
        "/// Errors that can occur during WAL record operations.\n///\n/// These errors typically occur during serialization or when attempting\n/// to process log records that exceed configured limits.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::wal::WalRecordError;\n/// // Error handling logic can match on these variants.\n/// ```\npub enum WalRecordError {"
    ),
    (
        "pub enum WalRecord {",
        "/// A log record in the Write-Ahead Log.\n///\n/// Each record represents a single logged operation. Records are serialized\n/// to the WAL file in order of their LSN.\n///\n/// Per Proscription 6, log records use relation names and serialized tuple\n/// data, never physical TupleId values. This maintains physical data\n/// independence - the logical layer has no knowledge of physical storage.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::wal::{WalRecord, TransactionId};\n///\n/// let txn_id = TransactionId::new(1);\n/// let record = WalRecord::Begin { txn_id };\n/// assert_eq!(record.txn_id(), Some(txn_id));\n/// ```\npub enum WalRecord {"
    )
])

# wal/recovery.rs
process_file("relvar-storage/src/wal/recovery.rs", [
    (
        "pub struct AnalysisResult {",
        "/// Result of the analysis pass during WAL recovery.\n///\n/// Summarizes the state of the write-ahead log, detailing committed\n/// and aborted transactions, and recording the final LSN.\n///\n/// # Examples\n///\n/// ```ignore\n/// use relvar_storage::wal::recovery::AnalysisResult;\n/// // Returned by the `analyze` function.\n/// ```\npub struct AnalysisResult {"
    ),
    (
        "pub struct UncommittedInsert {",
        "/// Represents an insert operation from an uncommitted transaction.\n///\n/// During recovery, these inserts must be undone (removed) from the physical\n/// storage to ensure atomicity.\n///\n/// # Examples\n///\n/// ```ignore\n/// use relvar_storage::wal::recovery::UncommittedInsert;\n/// // Processed by the recovery engine.\n/// ```\npub struct UncommittedInsert {"
    ),
    (
        "pub struct RecoveryResult {",
        "/// Result of the full recovery process.\n///\n/// Details the uncommitted operations that need to be undone and the LSN\n/// at which to resume normal logging operations.\n///\n/// # Examples\n///\n/// ```ignore\n/// use relvar_storage::wal::recovery::RecoveryResult;\n/// // Returned by the `recover` function.\n/// ```\npub struct RecoveryResult {"
    )
])

# wal/error.rs
process_file("relvar-storage/src/wal/error.rs", [
    (
        "pub enum WalError {",
        "/// Errors that can occur during Write-Ahead Logging operations.\n///\n/// This includes I/O failures, serialization issues, or unexpected EOF\n/// errors during crash recovery.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::wal::WalError;\n/// // Used throughout the WAL subsystem for robust error reporting.\n/// ```\npub enum WalError {"
    )
])

# mvcc/active_txn_table.rs
process_file("relvar-storage/src/mvcc/active_txn_table.rs", [
    (
        "pub struct ActiveTransactionTable {",
        "/// The Active Transaction Table (ATT) for Multi-Version Concurrency Control.\n///\n/// Tracks transactions that have begun but not yet committed or aborted. When a new\n/// transaction starts, it copies the keys of this table into its `TransactionSnapshot`.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::mvcc::ActiveTransactionTable;\n///\n/// let mut att = ActiveTransactionTable::new();\n/// assert!(att.oldest_active_lsn().is_none());\n/// ```\npub struct ActiveTransactionTable {"
    )
])

# mvcc/snapshot.rs
process_file("relvar-storage/src/mvcc/snapshot.rs", [
    (
        "pub struct TransactionSnapshot {",
        "/// Snapshot of transaction state at a point in time.\n///\n/// A transaction snapshot determines which tuple versions are visible to\n/// a transaction. It ensures snapshot isolation guarantees are met.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::mvcc::TransactionSnapshot;\n/// use relvar_storage::wal::{Lsn, TransactionId};\n///\n/// let snapshot = TransactionSnapshot::new(TransactionId::new(1), Lsn::new(10), vec![]);\n/// assert!(!snapshot.is_active(TransactionId::new(2)));\n/// ```\npub struct TransactionSnapshot {"
    )
])

# mvcc/visibility.rs
process_file("relvar-storage/src/mvcc/visibility.rs", [
    (
        "pub struct VersionMetadata {",
        "/// Metadata stored with every tuple version to implement MVCC visibility rules.\n///\n/// This header information determines if a tuple version is visible to a\n/// given transaction snapshot.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::mvcc::VersionMetadata;\n/// use relvar_storage::wal::TransactionId;\n///\n/// let meta = VersionMetadata { xmin: TransactionId::new(1), xmax: None };\n/// assert!(meta.xmax.is_none());\n/// ```\npub struct VersionMetadata {"
    )
])

# storage/heap.rs
process_file("relvar-storage/src/storage/heap.rs", [
    (
        "pub enum HeapError {",
        "/// Errors that can occur during heap file operations.\n///\n/// Handles page I/O issues, serialization failures, and capacity limits.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::storage::HeapError;\n/// // Used for propagating storage engine failures.\n/// ```\npub enum HeapError {"
    )
])

# storage/page.rs
process_file("relvar-storage/src/storage/page.rs", [
    (
        "pub enum PageError {",
        "/// Errors that can occur during page I/O operations.\n///\n/// Handles disk failures, corrupted pages, and capacity limits when\n/// working with `Page` and `PageFile` abstractions.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::storage::PageError;\n/// // Returned by the page buffering subsystem.\n/// ```\npub enum PageError {"
    ),
    (
        "pub struct Page {",
        "/// A single fixed-size data page.\n///\n/// Pages are the fundamental unit of I/O in the storage engine. They contain\n/// a header (tracking length) and an arbitrary data payload.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::storage::Page;\n///\n/// let page = Page::new(42);\n/// assert_eq!(page.id(), 42);\n/// assert!(page.is_empty());\n/// ```\npub struct Page {"
    )
])

# storage/catalog.rs
process_file("relvar-storage/src/storage/catalog.rs", [
    (
        "pub enum CatalogError {",
        "/// Errors that can occur during catalog operations.\n///\n/// Handles serialization failures, I/O errors, and logical violations like\n/// relation name collisions.\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::storage::CatalogError;\n/// // Encountered when metadata updates fail.\n/// ```\npub enum CatalogError {"
    ),
    (
        "pub struct RelationMetadata {",
        "/// Metadata for a stored relation (relvar).\n///\n/// Contains all the information needed to locate and interpret a relation's\n/// data on disk, including its heading and file path.\n///\n/// # Examples\n///\n/// ```ignore\n/// use relvar_storage::storage::RelationMetadata;\n/// // Retrieved via `Catalog::get_relation`.\n/// ```\npub struct RelationMetadata {"
    ),
    (
        "pub struct Catalog {",
        "/// The system catalog storing metadata for all relations in the database.\n///\n/// The catalog is the central registry for relation metadata. It maintains\n/// a mapping from relation names to their metadata (type and storage location).\n///\n/// # Examples\n///\n/// ```\n/// use relvar_storage::storage::Catalog;\n///\n/// let catalog = Catalog::new();\n/// assert_eq!(catalog.relation_count(), 0);\n/// ```\npub struct Catalog {"
    )
])
