//! Log Sequence Number (LSN) and Transaction ID types.
//!
//! These types provide unique identifiers for log records and transactions.

use serde::{Deserialize, Serialize};
use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};

/// Log Sequence Number - uniquely identifies a position in the WAL.
///
/// LSNs are monotonically increasing and provide a total ordering of
/// all log records. They are used to determine which operations happened
/// before others during recovery.
///
/// # Examples
///
/// ```
/// use relvar_storage::wal::Lsn;
///
/// let lsn1 = Lsn::new(1);
/// let lsn2 = Lsn::new(2);
///
/// assert!(lsn1 < lsn2);
/// assert_eq!(lsn1.next(), lsn2);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct Lsn(u64);

/// Unique identifier for a transaction.
///
/// TransactionIds are generated by `TransactionIdGenerator` and uniquely
/// identify a transaction within the database. They are separate from LSNs
/// because a single transaction may generate multiple log records.
///
/// # Examples
///
/// ```
/// use relvar_storage::wal::TransactionId;
///
/// let txn1 = TransactionId::new(1);
/// let txn2 = TransactionId::new(2);
///
/// assert_ne!(txn1, txn2);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct TransactionId(u64);

/// Generates unique transaction IDs using atomic operations.
///
/// This generator is thread-safe and guarantees that each transaction
/// receives a unique identifier.
pub struct TransactionIdGenerator {
    next_id: AtomicU64,
}

impl Lsn {
    /// Creates a new LSN with the given value.
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    /// Generates and provides the next sequential LSN.
    ///
    /// # Examples
    ///
    /// ```
    /// use relvar_storage::wal::Lsn;
    ///
    /// let lsn = Lsn::new(42);
    /// assert_eq!(lsn.next(), Lsn::new(43));
    /// ```
    pub fn next(self) -> Self {
        Self(self.0 + 1)
    }

    /// Extracts the raw numerical value of this `Lsn`.
    ///
    /// This is typically used when serializing the LSN into page headers or WAL records.
    ///
    /// # Examples
    ///
    /// ```
    /// use relvar_storage::wal::Lsn;
    ///
    /// let lsn = Lsn::new(42);
    /// assert_eq!(lsn.value(), 42);
    /// ```
    pub fn value(self) -> u64 {
        self.0
    }
}

impl TransactionId {
    /// Creates a new TransactionId with the given value.
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    /// Extracts the raw numerical value of this `TransactionId`.
    ///
    /// This is commonly used during serialization or when logging transaction details.
    ///
    /// # Examples
    ///
    /// ```
    /// use relvar_storage::wal::TransactionId;
    ///
    /// let txn = TransactionId::new(100);
    /// assert_eq!(txn.value(), 100);
    /// ```
    pub fn value(self) -> u64 {
        self.0
    }
}

impl TransactionIdGenerator {
    /// Creates a new transaction ID generator starting from 1.
    pub fn new() -> Self {
        Self {
            next_id: AtomicU64::new(1),
        }
    }

    /// Creates a new transaction ID generator starting from a specific ID.
    ///
    /// Used during recovery to continue from the maximum transaction ID
    /// seen in the WAL, preventing ID reuse.
    pub fn from_start(start_id: TransactionId) -> Self {
        Self {
            next_id: AtomicU64::new(start_id.value()),
        }
    }

    /// Generates the next unique transaction ID.
    ///
    /// This method is thread-safe and guarantees uniqueness.
    pub fn generate(&self) -> TransactionId {
        let id = self.next_id.fetch_add(1, Ordering::SeqCst);
        TransactionId(id)
    }
}

impl Default for TransactionIdGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for Lsn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "LSN({})", self.0)
    }
}

impl fmt::Display for TransactionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "TXN({})", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lsn_ordering() {
        let lsn1 = Lsn::new(1);
        let lsn2 = Lsn::new(2);
        let lsn3 = Lsn::new(3);

        assert!(lsn1 < lsn2);
        assert!(lsn2 < lsn3);
        assert!(lsn1 < lsn3);
        assert!(lsn2 > lsn1);
    }

    #[test]
    fn test_lsn_equality() {
        let lsn1 = Lsn::new(42);
        let lsn2 = Lsn::new(42);
        let lsn3 = Lsn::new(43);

        assert_eq!(lsn1, lsn2);
        assert_ne!(lsn1, lsn3);
    }

    #[test]
    fn test_lsn_increment() {
        let lsn = Lsn::new(100);
        assert_eq!(lsn.next(), Lsn::new(101));
        assert_eq!(lsn.next().next(), Lsn::new(102));
    }

    #[test]
    fn test_lsn_value() {
        let lsn = Lsn::new(42);
        assert_eq!(lsn.value(), 42);
    }

    #[test]
    fn test_transaction_id_uniqueness() {
        let generator = TransactionIdGenerator::new();

        let txn1 = generator.generate();
        let txn2 = generator.generate();
        let txn3 = generator.generate();

        assert_ne!(txn1, txn2);
        assert_ne!(txn2, txn3);
        assert_ne!(txn1, txn3);
    }

    #[test]
    fn test_transaction_id_sequential() {
        let generator = TransactionIdGenerator::new();

        let txn1 = generator.generate();
        let txn2 = generator.generate();

        assert_eq!(txn1.value() + 1, txn2.value());
    }

    #[test]
    fn test_transaction_id_equality() {
        let txn1 = TransactionId::new(42);
        let txn2 = TransactionId::new(42);
        let txn3 = TransactionId::new(43);

        assert_eq!(txn1, txn2);
        assert_ne!(txn1, txn3);
    }
}
