//! Log Sequence Numbers, transaction IDs, WAL records, and WAL framing.
//!
//! Moved from `relvar-storage`'s `wal/lsn.rs` and `wal/record.rs` into the
//! `no_std` storage core, adapting `std::` paths to `core::`/`alloc::`.
//! Two deliberate deviations from a verbatim move:
//!
//! * `WalRecord::Checkpoint.dirty_pages` uses [`hashbrown::HashMap`] instead
//!   of `std::collections::HashMap` (`std` is unavailable without the `std`
//!   feature). The postcard map encoding (varint length + entries) is
//!   unchanged, so on-disk bytes keep the same format.
//! * `Lsn::next`'s overflow path is spelled as an explicit `match` +
//!   `panic!` rather than `.expect()` — same message, same behavior —
//!   because the house rules forbid `.expect()` in non-test code.
//!
//! # WAL framing
//!
//! This module additionally defines the v0.7 WAL frame format. A v0.7 WAL
//! file is laid out as:
//!
//! ```text
//! [magic: 8 bytes][frame][frame]...
//! ```
//!
//! where `magic` is [`WAL_MAGIC_V2`] (`b"RELVAR02"`), and each frame is:
//!
//! ```text
//! [lsn: u64 LE][payload_len: u64 LE][postcard payload][crc32: u32 LE]
//! ```
//!
//! `payload_len` covers **only** the postcard bytes. The CRC-32 (IEEE,
//! [`crate::crc::crc32`]) covers `lsn` + `payload_len` + payload, so a torn
//! write — a partial frame at the tail — fails CRC verification instead of
//! decoding silently.
//!
//! Pre-v0.7 WAL files have **no** file magic and no CRC; their frames are
//! `[lsn: u64 LE][payload_len: u64 LE][postcard payload]`. Use
//! [`decode_legacy_frames`] to read those. Both decoders operate on the byte
//! stream *after* any file magic.
//!
//! # TTM Compliance
//!
//! Per Proscription 6, log records use relation names and serialized tuple
//! data, never physical TupleId values. This maintains physical data
//! independence — the logical layer has no knowledge of physical storage.

use crate::crc::crc32;
use alloc::string::String;
use alloc::vec::Vec;
use core::fmt;
use core::sync::atomic::{AtomicU64, Ordering};
use hashbrown::HashMap;
use serde::{Deserialize, Serialize};
use thiserror::Error;

// ---------------------------------------------------------------------------
// LSN and TransactionId (moved from wal/lsn.rs)
// ---------------------------------------------------------------------------

/// Log Sequence Number — uniquely identifies a position in the WAL.
///
/// LSNs are monotonically increasing and provide a total ordering of
/// all log records. They are used to determine which operations happened
/// before others during recovery.
///
/// # Examples
///
/// ```ignore
/// use relvar_storage_core::wal::Lsn;
///
/// let lsn1 = Lsn::new(1);
/// let lsn2 = Lsn::new(2);
///
/// assert!(lsn1 < lsn2);
/// assert_eq!(lsn1.next(), lsn2);
/// ```ignore
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct Lsn(u64);

/// Unique identifier for a transaction.
///
/// TransactionIds are generated by [`TransactionIdGenerator`] and uniquely
/// identify a transaction within the database. They are separate from LSNs
/// because a single transaction may generate multiple log records.
///
/// # Examples
///
/// ```ignore
/// use relvar_storage_core::wal::TransactionId;
///
/// let txn1 = TransactionId::new(1);
/// let txn2 = TransactionId::new(2);
///
/// assert_ne!(txn1, txn2);
/// ```ignore
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct TransactionId(u64);

/// Generates unique transaction IDs using atomic operations.
///
/// This generator is thread-safe and guarantees that each transaction
/// receives a unique identifier.
pub struct TransactionIdGenerator {
    next_id: AtomicU64,
}

impl Lsn {
    /// Creates a new LSN with the given value.
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::Lsn;
    /// let lsn = Lsn::new(42);
    /// assert_eq!(lsn.value(), 42);
    /// ```ignore
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    /// Generates and provides the next sequential LSN.
    ///
    /// # Panics
    ///
    /// Panics on `u64` overflow, which is unrecoverable (and unreachable in
    /// practice — it would require 2⁶⁴ log records).
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use relvar_storage_core::wal::Lsn;
    ///
    /// let lsn = Lsn::new(42);
    /// assert_eq!(lsn.next(), Lsn::new(43));
    /// ```ignore
    pub fn next(self) -> Self {
        // Spelled without `.expect()`: same message and behavior, but the
        // house rules forbid `.expect()` in non-test code.
        match self.0.checked_add(1) {
            Some(value) => Self(value),
            None => panic!("LSN overflow"),
        }
    }

    /// Extracts the raw numerical value of this `Lsn`.
    ///
    /// This is typically used when serializing the LSN into page headers or WAL records.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use relvar_storage_core::wal::Lsn;
    ///
    /// let lsn = Lsn::new(42);
    /// assert_eq!(lsn.value(), 42);
    /// ```ignore
    pub fn value(self) -> u64 {
        self.0
    }
}

impl TransactionId {
    /// Creates a new TransactionId with the given value.
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::TransactionId;
    /// let txn = TransactionId::new(100);
    /// assert_eq!(txn.value(), 100);
    /// ```ignore
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    /// Extracts the raw numerical value of this `TransactionId`.
    ///
    /// This is commonly used during serialization or when logging transaction details.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use relvar_storage_core::wal::TransactionId;
    ///
    /// let txn = TransactionId::new(100);
    /// assert_eq!(txn.value(), 100);
    /// ```ignore
    pub fn value(self) -> u64 {
        self.0
    }
}

impl TransactionIdGenerator {
    /// Creates a new transaction ID generator starting from 1.
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::TransactionIdGenerator;
    /// let generator = TransactionIdGenerator::new();
    /// assert_eq!(generator.generate().value(), 1);
    /// ```ignore
    pub fn new() -> Self {
        Self {
            next_id: AtomicU64::new(1),
        }
    }

    /// Creates a new transaction ID generator starting from a specific ID.
    ///
    /// Used during recovery to continue from the maximum transaction ID
    /// seen in the WAL, preventing ID reuse.
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::{TransactionId, TransactionIdGenerator};
    /// let generator = TransactionIdGenerator::from_start(TransactionId::new(50));
    /// assert_eq!(generator.generate().value(), 50);
    /// ```ignore
    pub fn from_start(start_id: TransactionId) -> Self {
        Self {
            next_id: AtomicU64::new(start_id.value()),
        }
    }

    /// Generates the next unique transaction ID.
    ///
    /// This method is thread-safe and guarantees uniqueness.
    ///
    /// # Panics
    ///
    /// Panics on `u64` overflow, which is unrecoverable.
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::TransactionIdGenerator;
    /// let generator = TransactionIdGenerator::new();
    /// let txn_id = generator.generate();
    /// assert_eq!(txn_id.value(), 1);
    /// ```ignore
    pub fn generate(&self) -> TransactionId {
        let id = self.next_id.fetch_add(1, Ordering::SeqCst);
        if id == u64::MAX {
            panic!("TransactionId overflow");
        }
        TransactionId(id)
    }

    /// Peeks at the next transaction ID without consuming it.
    ///
    /// This is the MVCC visibility horizon: every transaction that has begun
    /// so far holds an ID strictly less than the peeked value, so a snapshot
    /// stamped with this horizon hides versions created by transactions that
    /// begin afterwards — even if those transactions commit before the
    /// snapshot is read. This is what makes Repeatable Read actually repeat.
    pub fn peek_next(&self) -> TransactionId {
        TransactionId(self.next_id.load(Ordering::SeqCst))
    }
}

impl Default for TransactionIdGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for Lsn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "LSN({})", self.0)
    }
}

impl fmt::Display for TransactionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "TXN({})", self.0)
    }
}

// ---------------------------------------------------------------------------
// WalRecord (moved from wal/record.rs)
// ---------------------------------------------------------------------------

/// Errors that can occur during WAL record operations.
#[derive(Debug, Error)]
pub enum WalRecordError {
    /// Serialization error.
    #[error("Failed to serialize WAL record: {0}")]
    Serialization(#[from] postcard::Error),

    /// Record is too large to fit in buffer.
    #[error("WAL record too large: {0} bytes (max: {1})")]
    RecordTooLarge(usize, usize),
}

/// Maximum size of a single WAL record in bytes.
///
/// This is set to 1MB to allow for reasonable tuple sizes while preventing
/// unbounded memory usage.
pub const MAX_RECORD_SIZE: usize = 1024 * 1024; // 1MB

/// A log record in the Write-Ahead Log.
///
/// Each record represents a single logged operation. Records are serialized
/// to the WAL file in order of their LSN.
///
/// The variant order and field order are frozen: they determine the postcard
/// representation, so changing them would break byte-compatibility with
/// existing WAL files.
///
/// # TTM Compliance
///
/// Per Proscription 6, log records use relation names and serialized tuple
/// data, never physical TupleId values. This maintains physical data
/// independence - the logical layer has no knowledge of physical storage.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum WalRecord {
    /// Transaction begin marker.
    Begin {
        /// The transaction ID.
        txn_id: TransactionId,
    },

    /// Transaction commit marker.
    Commit {
        /// The transaction ID.
        txn_id: TransactionId,
    },

    /// Transaction abort marker.
    Abort {
        /// The transaction ID.
        txn_id: TransactionId,
    },

    /// A page write operation.
    ///
    /// Records the before-image of a page for undo recovery.
    PageWrite {
        /// The transaction ID.
        txn_id: TransactionId,
        /// The name of the relation being modified.
        relation_name: String,
        /// The page ID being written.
        page_id: u64,
        /// The page data (before-image for undo).
        page_data: Vec<u8>,
    },

    /// Insert a tuple into a relation.
    ///
    /// Records the serialized tuple data for redo recovery.
    /// The txn_id serves as xmin (creating transaction) for the version.
    Insert {
        /// The transaction ID (also serves as xmin for MVCC).
        txn_id: TransactionId,
        /// The name of the relation.
        relation_name: String,
        /// The serialized tuple data.
        tuple_data: Vec<u8>,
    },

    /// Update a tuple in a relation (MVCC version chain).
    ///
    /// Creates a new version and marks the old version as deleted.
    /// For MVCC recovery: old version gets xmax=txn_id, new version gets xmin=txn_id.
    Update {
        /// The transaction ID (xmin for new version, xmax for old version).
        txn_id: TransactionId,
        /// The name of the relation.
        relation_name: String,
        /// The serialized key values identifying the old version.
        /// Used during recovery to locate the old tuple and set its xmax.
        /// TTM Compliant: Uses logical key values, not physical TupleId.
        old_key_values: Vec<u8>,
        /// The serialized tuple data for the new version.
        new_tuple_data: Vec<u8>,
    },

    /// Delete a tuple from a relation.
    ///
    /// Records the key values needed to identify the tuple during recovery.
    Delete {
        /// The transaction ID.
        txn_id: TransactionId,
        /// The name of the relation.
        relation_name: String,
        /// The serialized key values identifying the tuple.
        key_values: Vec<u8>,
    },

    /// Checkpoint marker.
    ///
    /// Records the current state of dirty pages and active transactions.
    Checkpoint {
        /// The minimum LSN of any active transaction.
        min_active_lsn: Lsn,
        /// Dirty pages per relation.
        dirty_pages: HashMap<String, Vec<u64>>,
    },
}

impl WalRecord {
    /// Serializes this record to bytes using postcard.
    ///
    /// # Errors
    ///
    /// Returns `WalRecordError::Serialization` if serialization fails.
    /// Returns `WalRecordError::RecordTooLarge` if the record exceeds MAX_RECORD_SIZE.
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::{WalRecord, TransactionId};
    /// let record = WalRecord::Begin { txn_id: TransactionId::new(1) };
    /// let bytes = record.serialize().unwrap();
    /// assert!(!bytes.is_empty());
    /// ```ignore
    pub fn serialize(&self) -> Result<Vec<u8>, WalRecordError> {
        let bytes = postcard::to_allocvec(self)?;

        if bytes.len() > MAX_RECORD_SIZE {
            return Err(WalRecordError::RecordTooLarge(bytes.len(), MAX_RECORD_SIZE));
        }

        Ok(bytes)
    }

    /// Deserializes a record from bytes using postcard.
    ///
    /// # Errors
    ///
    /// Returns `WalRecordError::Serialization` if deserialization fails.
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::{WalRecord, TransactionId};
    /// let record = WalRecord::Begin { txn_id: TransactionId::new(1) };
    /// let bytes = record.serialize().unwrap();
    /// let deserialized = WalRecord::deserialize(&bytes).unwrap();
    /// assert_eq!(record.txn_id(), deserialized.txn_id());
    /// ```ignore
    pub fn deserialize(bytes: &[u8]) -> Result<Self, WalRecordError> {
        // Enforce maximum record size on the input buffer.
        if bytes.len() > MAX_RECORD_SIZE {
            return Err(WalRecordError::RecordTooLarge(bytes.len(), MAX_RECORD_SIZE));
        }

        // postcard handles limits internally.
        let record = postcard::from_bytes(bytes)?;
        Ok(record)
    }

    /// Extracts the associated `TransactionId` if the record belongs to a transaction.
    ///
    /// During the WAL analysis phase, this is used to identify which transaction
    /// created the record so the engine can track its commit/abort status. Note
    /// that some administrative records (like `Checkpoint`) are not bound to any
    /// specific transaction and will return `None`.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// use relvar_storage_core::wal::{WalRecord, TransactionId};
    ///
    /// let txn_id = TransactionId::new(5);
    /// let record = WalRecord::Begin { txn_id };
    ///
    /// assert_eq!(record.txn_id(), Some(txn_id));
    /// ```ignore
    ///
    /// Checkpoint records don't have a transaction ID.
    pub fn txn_id(&self) -> Option<TransactionId> {
        match self {
            WalRecord::Begin { txn_id }
            | WalRecord::Commit { txn_id }
            | WalRecord::Abort { txn_id }
            | WalRecord::PageWrite { txn_id, .. }
            | WalRecord::Insert { txn_id, .. }
            | WalRecord::Update { txn_id, .. }
            | WalRecord::Delete { txn_id, .. } => Some(*txn_id),
            WalRecord::Checkpoint { .. } => None,
        }
    }

    /// Returns true if this is a transaction end marker (commit or abort).
    ///
    /// # Examples
    /// ```ignore
    /// use relvar_storage_core::wal::{WalRecord, TransactionId};
    /// let commit = WalRecord::Commit { txn_id: TransactionId::new(1) };
    /// let abort = WalRecord::Abort { txn_id: TransactionId::new(1) };
    /// let begin = WalRecord::Begin { txn_id: TransactionId::new(1) };
    /// assert!(commit.is_txn_end());
    /// assert!(abort.is_txn_end());
    /// assert!(!begin.is_txn_end());
    /// ```ignore
    pub fn is_txn_end(&self) -> bool {
        matches!(self, WalRecord::Commit { .. } | WalRecord::Abort { .. })
    }
}

// ---------------------------------------------------------------------------
// WAL framing (new in v0.7)
// ---------------------------------------------------------------------------

/// File magic identifying a v0.7 WAL file with legacy (pre-CRC) framing.
///
/// Pre-v0.7 WAL files carry no file magic at all; this constant exists so a
/// v0.7 writer can explicitly label a file that uses the legacy
/// `[lsn][len][postcard]` frame layout (readable via
/// [`decode_legacy_frames`]).
pub const WAL_MAGIC_V1: &[u8; 8] = b"RELVAR01";

/// File magic identifying a v0.7 WAL file with CRC-32 frame framing.
///
/// A v0.7 WAL file starts with these 8 bytes, followed by frames as produced
/// by [`encode_frame`] and readable via [`decode_frames`].
pub const WAL_MAGIC_V2: &[u8; 8] = b"RELVAR02";

/// Errors that can occur during WAL frame encoding/decoding.
///
/// Core-only: no `std::io::Error` variant — I/O failures belong to the
/// [`crate::device::BlockDevice`] implementation on the host side.
#[derive(Debug, Error)]
pub enum WalError {
    /// A WAL record failed to serialize or deserialize.
    #[error("WAL record error: {0}")]
    Record(#[from] WalRecordError),

    /// Frame CRC-32 mismatch: the frame was torn or corrupted.
    ///
    /// A CRC mismatch is always reported as an error, never silently
    /// accepted — this is the torn-write detection.
    #[error(
        "CRC mismatch in WAL frame at offset {offset}: expected {expected:#010x}, computed {actual:#010x}"
    )]
    CrcMismatch {
        /// Byte offset of the frame within the decoded buffer.
        offset: usize,
        /// CRC-32 stored at the end of the frame.
        expected: u32,
        /// CRC-32 computed over the frame's headers + payload.
        actual: u32,
    },

    /// The buffer ends mid-frame: a torn write at the tail.
    #[error("Truncated WAL frame at offset {0}")]
    Truncated(usize),

    /// The frame's declared payload length exceeds [`MAX_RECORD_SIZE`].
    #[error("WAL frame payload length {0} exceeds maximum record size")]
    PayloadTooLarge(u64),
}

/// Encodes a WAL record as a v2 frame.
///
/// Frame layout: `[lsn: u64 LE][payload_len: u64 LE][postcard payload][crc32: u32 LE]`.
/// `payload_len` covers only the postcard bytes; the CRC-32 (IEEE) covers
/// `lsn` + `payload_len` + payload.
///
/// # Errors
///
/// Returns [`WalError::Record`] if the record cannot be serialized or
/// exceeds [`MAX_RECORD_SIZE`].
///
/// # Examples
///
/// ```
/// use relvar_storage_core::wal::{Lsn, TransactionId, WalRecord, decode_frames, encode_frame};
///
/// let record = WalRecord::Begin { txn_id: TransactionId::new(1) };
/// let frame = encode_frame(Lsn::new(7), &record).unwrap();
///
/// let decoded: Vec<_> = decode_frames(&frame).collect();
/// assert_eq!(decoded.len(), 1);
/// let (lsn, decoded_record) = decoded.into_iter().next().unwrap().unwrap();
/// assert_eq!(lsn, Lsn::new(7));
/// assert_eq!(decoded_record, record);
/// ```
pub fn encode_frame(lsn: Lsn, record: &WalRecord) -> Result<Vec<u8>, WalError> {
    let payload = record.serialize()?;

    let mut frame = Vec::with_capacity(8 + 8 + payload.len() + 4);
    frame.extend_from_slice(&lsn.value().to_le_bytes());
    frame.extend_from_slice(&(payload.len() as u64).to_le_bytes());
    frame.extend_from_slice(&payload);
    // CRC covers lsn_bytes + len_bytes + payload (everything so far).
    let checksum = crc32(&frame);
    frame.extend_from_slice(&checksum.to_le_bytes());
    Ok(frame)
}

/// Reads a little-endian `u64` at `offset`, or `None` if out of bounds.
fn read_u64_le(data: &[u8], offset: usize) -> Option<u64> {
    let bytes: [u8; 8] = data.get(offset..offset + 8)?.try_into().ok()?;
    Some(u64::from_le_bytes(bytes))
}

/// Reads a little-endian `u32` at `offset`, or `None` if out of bounds.
fn read_u32_le(data: &[u8], offset: usize) -> Option<u32> {
    let bytes: [u8; 4] = data.get(offset..offset + 4)?.try_into().ok()?;
    Some(u32::from_le_bytes(bytes))
}

/// Iterator over v2 WAL frames in a byte buffer.
///
/// Yields `Ok((Lsn, WalRecord))` per frame. The first corrupt frame yields
/// an `Err` and then the iterator stops: a torn or corrupted frame means
/// every byte after it is suspect, so recovery must not continue past it.
/// An empty tail (offset exactly at end of buffer) is a clean end and
/// yields `None`.
pub struct FrameDecoder<'a> {
    data: &'a [u8],
    offset: usize,
    failed: bool,
}

impl<'a> FrameDecoder<'a> {
    /// Creates a decoder over `data` (the byte stream after any file magic).
    fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            offset: 0,
            failed: false,
        }
    }
}

impl Iterator for FrameDecoder<'_> {
    type Item = Result<(Lsn, WalRecord), WalError>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.failed {
            return None;
        }
        // After the first error the iterator is fused: report the error once,
        // then stop.
        let fail = |decoder: &mut Self, error: WalError| {
            decoder.failed = true;
            Some(Err(error))
        };

        let offset = self.offset;
        if offset == self.data.len() {
            return None; // Clean end of stream.
        }

        let lsn_value = match read_u64_le(self.data, offset) {
            Some(value) => value,
            None => return fail(self, WalError::Truncated(offset)),
        };
        let payload_len_u64 = match read_u64_le(self.data, offset + 8) {
            Some(value) => value,
            None => return fail(self, WalError::Truncated(offset)),
        };
        if payload_len_u64 > MAX_RECORD_SIZE as u64 {
            return fail(self, WalError::PayloadTooLarge(payload_len_u64));
        }
        let payload_len = match usize::try_from(payload_len_u64) {
            Ok(len) => len,
            Err(_) => return fail(self, WalError::PayloadTooLarge(payload_len_u64)),
        };

        let payload_end = match (offset + 16).checked_add(payload_len) {
            Some(end) => end,
            None => return fail(self, WalError::Truncated(offset)),
        };
        let frame_end = match payload_end.checked_add(4) {
            Some(end) => end,
            None => return fail(self, WalError::Truncated(offset)),
        };
        if frame_end > self.data.len() {
            // Torn write: the frame's bytes never fully landed.
            return fail(self, WalError::Truncated(offset));
        }

        let expected = match read_u32_le(self.data, payload_end) {
            Some(value) => value,
            None => return fail(self, WalError::Truncated(offset)),
        };
        let actual = crc32(&self.data[offset..payload_end]);
        if expected != actual {
            return fail(
                self,
                WalError::CrcMismatch {
                    offset,
                    expected,
                    actual,
                },
            );
        }

        let record = match WalRecord::deserialize(&self.data[offset + 16..payload_end]) {
            Ok(record) => record,
            Err(error) => return fail(self, WalError::Record(error)),
        };

        self.offset = frame_end;
        Some(Ok((Lsn::new(lsn_value), record)))
    }
}

/// Decodes v2 WAL frames from a byte buffer.
///
/// Each frame is verified with CRC-32; a torn or corrupted frame yields an
/// error (never a silent mis-decode) and stops the iterator. Operates on
/// the byte stream *after* any 8-byte file magic.
///
/// # Examples
///
/// ```
/// use relvar_storage_core::wal::{Lsn, TransactionId, WalRecord, decode_frames, encode_frame};
///
/// let frames: Vec<u8> = [1u64, 2, 3]
///     .into_iter()
///     .flat_map(|i| {
///         encode_frame(
///             Lsn::new(i),
///             &WalRecord::Commit { txn_id: TransactionId::new(i) },
///         )
///         .unwrap()
///     })
///     .collect();
///
/// let decoded: Vec<_> = decode_frames(&frames)
///     .collect::<Result<_, _>>()
///     .unwrap();
/// assert_eq!(decoded.len(), 3);
/// assert_eq!(decoded[0].0, Lsn::new(1));
/// ```
pub fn decode_frames(data: &[u8]) -> FrameDecoder<'_> {
    FrameDecoder::new(data)
}

/// Iterator over legacy (pre-v0.7) WAL frames in a byte buffer.
///
/// Legacy frames are `[lsn: u64 LE][payload_len: u64 LE][postcard payload]`
/// with no CRC and no file magic. A buffer shorter than the 16-byte header
/// is treated as a clean end; a frame that extends past the buffer yields
/// an error and stops the iterator (mirroring the old recovery behavior of
/// treating a torn tail as the end of the valid log).
pub struct LegacyFrameDecoder<'a> {
    data: &'a [u8],
    offset: usize,
    failed: bool,
}

impl<'a> LegacyFrameDecoder<'a> {
    /// Creates a decoder over `data` (the raw legacy WAL bytes).
    fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            offset: 0,
            failed: false,
        }
    }
}

impl Iterator for LegacyFrameDecoder<'_> {
    type Item = Result<(Lsn, WalRecord), WalError>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.failed {
            return None;
        }
        let fail = |decoder: &mut Self, error: WalError| {
            decoder.failed = true;
            Some(Err(error))
        };

        let offset = self.offset;
        // Need at least 16 bytes for LSN (8) + length (8); a short tail is a
        // clean end (torn header bytes simply never landed).
        if offset + 16 > self.data.len() {
            return None;
        }

        let lsn_value = match read_u64_le(self.data, offset) {
            Some(value) => value,
            None => return fail(self, WalError::Truncated(offset)),
        };
        let payload_len_u64 = match read_u64_le(self.data, offset + 8) {
            Some(value) => value,
            None => return fail(self, WalError::Truncated(offset)),
        };
        if payload_len_u64 > MAX_RECORD_SIZE as u64 {
            return fail(self, WalError::PayloadTooLarge(payload_len_u64));
        }
        let payload_len = match usize::try_from(payload_len_u64) {
            Ok(len) => len,
            Err(_) => return fail(self, WalError::PayloadTooLarge(payload_len_u64)),
        };

        let payload_end = match (offset + 16).checked_add(payload_len) {
            Some(end) => end,
            None => return fail(self, WalError::Truncated(offset)),
        };
        if payload_end > self.data.len() {
            // Torn tail: the old recovery code surfaced this as corruption
            // and stopped the scan at the last valid record.
            return fail(self, WalError::Truncated(offset));
        }

        let record = match WalRecord::deserialize(&self.data[offset + 16..payload_end]) {
            Ok(record) => record,
            Err(error) => return fail(self, WalError::Record(error)),
        };

        self.offset = payload_end;
        Some(Ok((Lsn::new(lsn_value), record)))
    }
}

/// Decodes legacy (pre-v0.7) WAL frames from a byte buffer.
///
/// Legacy format: `[lsn: u64 LE][payload_len: u64 LE][postcard payload]`,
/// no CRC, no file magic. This is the read path for WAL files written
/// before v0.7.
pub fn decode_legacy_frames(data: &[u8]) -> LegacyFrameDecoder<'_> {
    LegacyFrameDecoder::new(data)
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    // ---- Lsn / TransactionId (moved from lsn.rs tests) ----

    #[test]
    fn test_lsn_ordering() {
        let lsn1 = Lsn::new(1);
        let lsn2 = Lsn::new(2);
        let lsn3 = Lsn::new(3);

        assert!(lsn1 < lsn2);
        assert!(lsn2 < lsn3);
        assert!(lsn1 < lsn3);
        assert!(lsn2 > lsn1);
    }

    #[test]
    fn test_lsn_equality() {
        let lsn1 = Lsn::new(42);
        let lsn2 = Lsn::new(42);
        let lsn3 = Lsn::new(43);

        assert_eq!(lsn1, lsn2);
        assert_ne!(lsn1, lsn3);
    }

    #[test]
    fn test_lsn_increment() {
        let lsn = Lsn::new(100);
        assert_eq!(lsn.next(), Lsn::new(101));
        assert_eq!(lsn.next().next(), Lsn::new(102));
    }

    #[test]
    fn test_lsn_value() {
        let lsn = Lsn::new(42);
        assert_eq!(lsn.value(), 42);
    }

    #[test]
    fn test_transaction_id_uniqueness() {
        let generator = TransactionIdGenerator::new();

        let txn1 = generator.generate();
        let txn2 = generator.generate();
        let txn3 = generator.generate();

        assert_ne!(txn1, txn2);
        assert_ne!(txn2, txn3);
        assert_ne!(txn1, txn3);
    }

    #[test]
    fn test_transaction_id_sequential() {
        let generator = TransactionIdGenerator::new();

        let txn1 = generator.generate();
        let txn2 = generator.generate();

        assert_eq!(txn1.value() + 1, txn2.value());
    }

    #[test]
    fn test_transaction_id_equality() {
        let txn1 = TransactionId::new(42);
        let txn2 = TransactionId::new(42);
        let txn3 = TransactionId::new(43);

        assert_eq!(txn1, txn2);
        assert_ne!(txn1, txn3);
    }

    #[test]
    fn test_transaction_id_generator_default() {
        let generator = TransactionIdGenerator::default();
        assert_eq!(generator.generate().value(), 1);
    }

    #[test]
    fn test_lsn_display() {
        let lsn = Lsn::new(42);
        assert_eq!(format!("{}", lsn), "LSN(42)");
    }

    #[test]
    fn test_transaction_id_display() {
        let txn_id = TransactionId::new(42);
        assert_eq!(format!("{}", txn_id), "TXN(42)");
    }

    #[test]
    #[should_panic(expected = "TransactionId overflow")]
    fn test_transaction_id_generator_overflow() {
        let generator = TransactionIdGenerator::from_start(TransactionId::new(u64::MAX));
        generator.generate();
    }

    // ---- WalRecord (moved from record.rs tests) ----

    #[test]
    fn test_record_roundtrip_begin() {
        let txn_id = TransactionId::new(1);
        let record = WalRecord::Begin { txn_id };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);
    }

    #[test]
    fn test_record_roundtrip_commit() {
        let txn_id = TransactionId::new(42);
        let record = WalRecord::Commit { txn_id };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);
    }

    #[test]
    fn test_record_roundtrip_abort() {
        let txn_id = TransactionId::new(99);
        let record = WalRecord::Abort { txn_id };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);
    }

    #[test]
    fn test_record_roundtrip_insert() {
        let txn_id = TransactionId::new(1);
        let tuple_data = vec![1, 2, 3, 4, 5];
        let record = WalRecord::Insert {
            txn_id,
            relation_name: String::from("employees"),
            tuple_data: tuple_data.clone(),
        };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);

        // Verify tuple_data is preserved
        if let WalRecord::Insert {
            tuple_data: recovered_data,
            ..
        } = deserialized
        {
            assert_eq!(tuple_data, recovered_data);
        } else {
            panic!("Expected Insert record");
        }
    }

    #[test]
    fn test_record_roundtrip_delete() {
        let txn_id = TransactionId::new(1);
        let key_values = vec![42, 43, 44];
        let record = WalRecord::Delete {
            txn_id,
            relation_name: String::from("employees"),
            key_values: key_values.clone(),
        };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);
    }

    #[test]
    fn test_record_roundtrip_page_write() {
        let txn_id = TransactionId::new(1);
        let page_data = vec![0u8; 4096]; // Simulated page
        let record = WalRecord::PageWrite {
            txn_id,
            relation_name: String::from("employees"),
            page_id: 5,
            page_data: page_data.clone(),
        };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);
    }

    #[test]
    fn test_record_roundtrip_checkpoint() {
        let mut dirty_pages = HashMap::new();
        dirty_pages.insert(String::from("employees"), vec![1, 2]);
        dirty_pages.insert(String::from("departments"), vec![3]);

        let record = WalRecord::Checkpoint {
            min_active_lsn: Lsn::new(100),
            dirty_pages,
        };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);
    }

    #[test]
    fn test_record_size_bounded() {
        // Small record should succeed
        let small_record = WalRecord::Begin {
            txn_id: TransactionId::new(1),
        };
        assert!(small_record.serialize().is_ok());

        // Large record should fail
        let huge_data = vec![0u8; MAX_RECORD_SIZE + 1];
        let large_record = WalRecord::Insert {
            txn_id: TransactionId::new(1),
            relation_name: String::from("test"),
            tuple_data: huge_data,
        };

        let result = large_record.serialize();
        assert!(result.is_err());
        assert!(matches!(result, Err(WalRecordError::RecordTooLarge(_, _))));
    }

    #[test]
    fn test_txn_id_extraction() {
        let txn_id = TransactionId::new(42);

        assert_eq!(WalRecord::Begin { txn_id }.txn_id(), Some(txn_id));
        assert_eq!(WalRecord::Commit { txn_id }.txn_id(), Some(txn_id));
        assert_eq!(WalRecord::Abort { txn_id }.txn_id(), Some(txn_id));
        assert_eq!(
            WalRecord::Insert {
                txn_id,
                relation_name: String::from("test"),
                tuple_data: vec![],
            }
            .txn_id(),
            Some(txn_id)
        );

        // Checkpoint has no transaction ID
        assert_eq!(
            WalRecord::Checkpoint {
                min_active_lsn: Lsn::new(1),
                dirty_pages: HashMap::new(),
            }
            .txn_id(),
            None
        );
    }

    #[test]
    fn test_is_txn_end() {
        let txn_id = TransactionId::new(1);

        assert!(!WalRecord::Begin { txn_id }.is_txn_end());
        assert!(WalRecord::Commit { txn_id }.is_txn_end());
        assert!(WalRecord::Abort { txn_id }.is_txn_end());
        assert!(
            !WalRecord::Insert {
                txn_id,
                relation_name: String::from("test"),
                tuple_data: vec![],
            }
            .is_txn_end()
        );
    }

    #[test]
    fn test_update_record_roundtrip() {
        let txn_id = TransactionId::new(5);
        // Use serialized key values instead of physical TupleId (TTM compliant)
        let old_key_values = vec![99, 98, 97];
        let new_tuple_data = vec![10, 20, 30];

        let record = WalRecord::Update {
            txn_id,
            relation_name: String::from("employees"),
            old_key_values,
            new_tuple_data: new_tuple_data.clone(),
        };

        let bytes = record.serialize().expect("serialization failed");
        let deserialized = WalRecord::deserialize(&bytes).expect("deserialization failed");

        assert_eq!(record, deserialized);
    }

    #[test]
    fn test_wal_record_deserialize_errors() {
        let invalid_bytes = vec![255, 255, 255, 255]; // Invalid postcard data
        let result = WalRecord::deserialize(&invalid_bytes);
        assert!(matches!(result, Err(WalRecordError::Serialization(_))));
    }

    #[test]
    fn test_is_txn_end_other_variants() {
        let txn_id = TransactionId::new(1);

        let page_write = WalRecord::PageWrite {
            txn_id,
            relation_name: String::from("test"),
            page_id: 1,
            page_data: vec![],
        };
        assert!(!page_write.is_txn_end());

        let delete = WalRecord::Delete {
            txn_id,
            relation_name: String::from("test"),
            key_values: vec![],
        };
        assert!(!delete.is_txn_end());

        let checkpoint = WalRecord::Checkpoint {
            min_active_lsn: Lsn::new(1),
            dirty_pages: HashMap::new(),
        };
        assert!(!checkpoint.is_txn_end());
    }

    #[test]
    fn test_record_txn_id_page_write_and_delete() {
        let txn_id = TransactionId::new(123);
        let record_page_write = WalRecord::PageWrite {
            txn_id,
            relation_name: String::from("test"),
            page_id: 1,
            page_data: vec![1, 2, 3],
        };
        let record_delete = WalRecord::Delete {
            txn_id,
            relation_name: String::from("test"),
            key_values: vec![1, 2, 3],
        };

        assert_eq!(record_page_write.txn_id(), Some(txn_id));
        assert_eq!(record_delete.txn_id(), Some(txn_id));
    }

    #[test]
    fn test_allocation_bomb_prevention() {
        let mut payload = Vec::new();
        // Insert variant (4)
        payload.push(4u8);
        // txn_id (1)
        payload.extend_from_slice(&postcard::to_allocvec(&1u64).unwrap());
        // relation_name "test"
        payload.extend_from_slice(&postcard::to_allocvec("test").unwrap());

        let result = WalRecord::deserialize(&payload);

        match result {
            Err(WalRecordError::Serialization(_e)) => {}
            _ => panic!("Expected Serialization error, got {:?}", result),
        }
    }

    #[test]
    fn test_wal_record_error_display() {
        let err1 = WalRecordError::Serialization(postcard::Error::DeserializeUnexpectedEnd);
        assert_eq!(
            err1.to_string(),
            "Failed to serialize WAL record: Hit the end of buffer, expected more data"
        );

        let err2 = WalRecordError::RecordTooLarge(1500000, 1048576);
        assert_eq!(
            err2.to_string(),
            "WAL record too large: 1500000 bytes (max: 1048576)"
        );
    }

    // ---- v2 framing ----

    fn sample_records() -> Vec<(Lsn, WalRecord)> {
        vec![
            (
                Lsn::new(1),
                WalRecord::Begin {
                    txn_id: TransactionId::new(1),
                },
            ),
            (
                Lsn::new(2),
                WalRecord::Insert {
                    txn_id: TransactionId::new(1),
                    relation_name: String::from("employees"),
                    tuple_data: vec![10, 20, 30],
                },
            ),
            (
                Lsn::new(3),
                WalRecord::Commit {
                    txn_id: TransactionId::new(1),
                },
            ),
        ]
    }

    #[test]
    fn test_frame_layout_is_exact() {
        let record = WalRecord::Begin {
            txn_id: TransactionId::new(9),
        };
        let payload = record.serialize().unwrap();
        let frame = encode_frame(Lsn::new(0x0102_0304_0506_0708), &record).unwrap();

        // [lsn:8 LE][payload_len:8 LE][payload][crc32:4 LE]
        assert_eq!(frame.len(), 8 + 8 + payload.len() + 4);
        assert_eq!(
            u64::from_le_bytes(frame[0..8].try_into().unwrap()),
            0x0102_0304_0506_0708
        );
        assert_eq!(
            u64::from_le_bytes(frame[8..16].try_into().unwrap()),
            payload.len() as u64,
            "payload_len must cover only the postcard bytes"
        );
        assert_eq!(&frame[16..16 + payload.len()], payload.as_slice());

        // CRC covers lsn_bytes + len_bytes + payload.
        let expected_crc = crc32(&frame[..16 + payload.len()]);
        let stored_crc = u32::from_le_bytes(frame[16 + payload.len()..].try_into().unwrap());
        assert_eq!(stored_crc, expected_crc);
    }

    #[test]
    fn test_frame_roundtrip_multiple() {
        let mut stream = Vec::new();
        for (lsn, record) in sample_records() {
            stream.extend_from_slice(&encode_frame(lsn, &record).unwrap());
        }

        let decoded: Vec<(Lsn, WalRecord)> = decode_frames(&stream)
            .collect::<Result<_, _>>()
            .expect("frames should decode");
        assert_eq!(decoded, sample_records());
    }

    #[test]
    fn test_frame_empty_stream_decodes_cleanly() {
        let decoded: Vec<_> = decode_frames(&[]).collect();
        assert!(decoded.is_empty());
    }

    #[test]
    fn test_frame_crc_mismatch_in_payload_is_error() {
        let record = WalRecord::Begin {
            txn_id: TransactionId::new(1),
        };
        let mut frame = encode_frame(Lsn::new(1), &record).unwrap();
        // Frame layout is [lsn: 8][len: 8][payload][crc: 4]: corrupt the
        // first payload byte (offset 16), which cannot be the CRC field.
        assert!(frame.len() > 16 + 4, "frame must contain a payload byte");
        frame[16] ^= 0xFF;

        let mut decoder = decode_frames(&frame);
        let first = decoder.next().expect("iterator must yield the error");
        assert!(
            matches!(first, Err(WalError::CrcMismatch { .. })),
            "expected CrcMismatch, got {:?}",
            first
        );
        // The iterator stops after the first corrupt frame.
        assert!(decoder.next().is_none());
    }

    #[test]
    fn test_frame_crc_mismatch_in_header_is_error() {
        let record = WalRecord::Commit {
            txn_id: TransactionId::new(2),
        };
        let mut frame = encode_frame(Lsn::new(5), &record).unwrap();
        // Corrupt the LSN header byte; CRC covers headers too.
        frame[3] ^= 0x01;

        let result: Vec<_> = decode_frames(&frame).collect();
        assert_eq!(result.len(), 1);
        assert!(matches!(result[0], Err(WalError::CrcMismatch { .. })));
    }

    #[test]
    fn test_frame_crc_mismatch_in_crc_field_is_error() {
        let record = WalRecord::Abort {
            txn_id: TransactionId::new(3),
        };
        let mut frame = encode_frame(Lsn::new(6), &record).unwrap();
        let last = frame.len() - 1;
        frame[last] ^= 0x01;

        let result: Vec<_> = decode_frames(&frame).collect();
        assert_eq!(result.len(), 1);
        assert!(matches!(result[0], Err(WalError::CrcMismatch { .. })));
    }

    #[test]
    fn test_frame_truncated_tail_is_error() {
        let mut stream = Vec::new();
        for (lsn, record) in sample_records() {
            stream.extend_from_slice(&encode_frame(lsn, &record).unwrap());
        }
        // Simulate a torn write: chop the last frame in half.
        stream.truncate(stream.len() - 10);

        let results: Vec<_> = decode_frames(&stream).collect();
        // Two good frames, then the torn tail surfaces as an error.
        assert_eq!(results.len(), 3);
        assert!(results[0].is_ok());
        assert!(results[1].is_ok());
        assert!(matches!(results[2], Err(WalError::Truncated(_))));
    }

    #[test]
    fn test_frame_truncated_header_is_error() {
        let results: Vec<_> = decode_frames(&[1, 2, 3, 4, 5]).collect();
        assert_eq!(results.len(), 1);
        assert!(matches!(results[0], Err(WalError::Truncated(_))));
    }

    #[test]
    fn test_frame_payload_too_large_is_error() {
        let mut frame = Vec::new();
        frame.extend_from_slice(&1u64.to_le_bytes());
        frame.extend_from_slice(&((MAX_RECORD_SIZE + 1) as u64).to_le_bytes());

        let results: Vec<_> = decode_frames(&frame).collect();
        assert_eq!(results.len(), 1);
        assert!(matches!(results[0], Err(WalError::PayloadTooLarge(_))));
    }

    #[test]
    fn test_frame_oversize_record_encode_fails() {
        let record = WalRecord::Insert {
            txn_id: TransactionId::new(1),
            relation_name: String::from("huge"),
            tuple_data: vec![0u8; MAX_RECORD_SIZE + 1],
        };
        let result = encode_frame(Lsn::new(1), &record);
        assert!(matches!(result, Err(WalError::Record(_))));
    }

    #[test]
    fn test_wal_magic_constants() {
        assert_eq!(WAL_MAGIC_V1, b"RELVAR01");
        assert_eq!(WAL_MAGIC_V2, b"RELVAR02");
        assert_ne!(WAL_MAGIC_V1, WAL_MAGIC_V2);
    }

    // ---- legacy framing ----

    /// Encodes one legacy frame by hand: [lsn:8 LE][len:8 LE][postcard].
    fn encode_legacy_frame(lsn: Lsn, record: &WalRecord) -> Vec<u8> {
        let payload = record.serialize().unwrap();
        let mut frame = Vec::new();
        frame.extend_from_slice(&lsn.value().to_le_bytes());
        frame.extend_from_slice(&(payload.len() as u64).to_le_bytes());
        frame.extend_from_slice(&payload);
        frame
    }

    #[test]
    fn test_legacy_frames_decode() {
        let mut stream = Vec::new();
        for (lsn, record) in sample_records() {
            stream.extend_from_slice(&encode_legacy_frame(lsn, &record));
        }

        let decoded: Vec<(Lsn, WalRecord)> = decode_legacy_frames(&stream)
            .collect::<Result<_, _>>()
            .expect("legacy frames should decode");
        assert_eq!(decoded, sample_records());
    }

    #[test]
    fn test_legacy_empty_stream_decodes_cleanly() {
        assert!(decode_legacy_frames(&[]).next().is_none());
        // A short tail (< 16 bytes) is a clean end, not an error.
        assert!(decode_legacy_frames(&[1, 2, 3]).next().is_none());
    }

    #[test]
    fn test_legacy_truncated_record_is_error() {
        let mut stream = encode_legacy_frame(
            Lsn::new(1),
            &WalRecord::Begin {
                txn_id: TransactionId::new(1),
            },
        );
        // Declare the right length but chop one payload byte: torn write.
        stream.truncate(stream.len() - 1);

        let results: Vec<_> = decode_legacy_frames(&stream).collect();
        assert_eq!(results.len(), 1);
        assert!(matches!(results[0], Err(WalError::Truncated(_))));
    }

    #[test]
    fn test_legacy_matches_old_writer_byte_for_byte() {
        // Reproduces exactly what relvar-storage's WalManager::log wrote:
        // [lsn (8 bytes)][record_len (8 bytes)][record_data].
        let record = WalRecord::Insert {
            txn_id: TransactionId::new(4),
            relation_name: String::from("departments"),
            tuple_data: vec![7, 8, 9],
        };
        let payload = record.serialize().unwrap();

        let mut old_format = Vec::new();
        old_format.extend_from_slice(&42u64.to_le_bytes());
        old_format.extend_from_slice(&(payload.len() as u64).to_le_bytes());
        old_format.extend_from_slice(&payload);

        let decoded: Vec<_> = decode_legacy_frames(&old_format)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(decoded.len(), 1);
        assert_eq!(decoded[0].0, Lsn::new(42));
        assert_eq!(decoded[0].1, record);
    }
}
